project_name: mogan
env:
  - CGO_ENABLED=1
builds:
  - id: darwin-amd64
    main: ./cmd/mogan
    binary: mogan
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
  - id: darwin-arm64
    main: ./cmd/mogan
    binary: mogan
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
  - id: linux-amd64
    main: ./cmd/mogan
    binary: mogan
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
  # Use armhfv6 for all armhf systems with v6+ architecture
  - id: linux-armhfv6
    main: ./cmd/mogan
    binary: mogan
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
  # Use armhfv7 for all armhf systems with v7+ architecture
  - id: linux-armhfv7
    main: ./cmd/mogan
    binary: mogan
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
  # Use arm64 for all v8 64-bit architectures
  - id: linux-arm64
    main: ./cmd/mogan
    binary: mogan
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
  - id: windows-amd64
    main: ./cmd/mogan
    binary: mogan
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
    ldflags:
      - -buildmode=exe
archives:
  - id: mogan-armhfv6
    builds:
      - linux-armhfv6
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_armhfv6"
    wrap_in_directory: true
  - id: mogan-armhfv7
    builds:
      - linux-armhfv7
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_armhfv7"
    wrap_in_directory: true
  - id: mogan
    builds:
      - darwin-amd64
      - darwin-arm64
      - windows-amd64
      - linux-amd64
      - linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - maintainer: Dmitry Aladin <anon.digriz@gmail.com>
    description: Local editor of the Multidimensional Open Gnoseological Active Network (MOGAN).
    homepage: https://github.com/anondigriz/mogan-mini
    license: MPL-2.0 license
